### ISSUE TITLE
error msg="Zone not found, skipping domain test.example.com"

### ISSUE THREAD

**Issue by Hitman247m** [juusujanar/cloudflare-ddns#17]
Hey,

I was hoping I could get some help with the issue. I'm using version 2.0 of the container, and I'm unable to update a subdomain with the tool. I see this error in the container logs:

`
level=error msg="Zone not found, skipping domain test.example.com"
`

My config.yml file looks like this:
```
domains:
  - name: test.example.com
    ttl: 3600
    ipv6: false
    proxied: false
email: <ACCOUNT-EMAIL>
token: <GLOBAL-TOKEN>
```

**Comment by juusujanar** [comment]
Hi, @Hitman247m

Sorry for the late reply. Are you still having the issue?

**Comment by Hitman247m** [comment]
@juusujanar Not a problem, I'm not currently using it. You can close this.

**Comment by juusujanar** [comment]
All right, closing. Feel free to open a new issue if it occurs again.

**Comment by ConorIA** [comment]
Hi, found this issue after trying the container. I also can't use the app for the same reason. The CF zone is, e.g. domain.com; my config: 

```
domains:
  - name: subdomain.domain.com
    ttl: 3600
    ipv6: false
    proxied: false
email: <REDACTED>
token: <REDACTED>
```

The container logs: 

```
time="2021-01-08T13:30:47Z" level=error msg="Zone not found, skipping domain subdomain.domain.com"
time="2021-01-08T13:30:57Z" level=info msg="Valid IPv4 received, updating A records to <REDACTED>"
```

However the A record for subdomain.domain.com does not update, notwithstanding the second log line.
